[project]
name = 'Decentralized-Public-Service-Performance-Tracking-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.agency-verificaiton]
path = 'contracts/agency-verificaiton.clar'
clarity_version = 2
epoch = 2.5

[contracts.data-collection]
path = 'contracts/data-collection.clar'
clarity_version = 2
epoch = 2.5

[contracts.performance-metrics]
path = 'contracts/performance-metrics.clar'
clarity_version = 2
epoch = 2.5

[contracts.reporting]
path = 'contracts/reporting.clar'
clarity_version = 2
epoch = 2.5

[contracts.service-registration]
path = 'contracts/service-registration.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
